#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env"
EXAMPLE_FILE=".env.example"

if [[ ! -f "$EXAMPLE_FILE" ]]; then
  echo "ERROR: $EXAMPLE_FILE not found"
  exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

default_timezone() {
  if [[ -n "${TZ:-}" ]]; then
    printf '%s' "$TZ"
  elif [[ -f /etc/timezone ]]; then
    tr -d '\n' < /etc/timezone
  elif command -v timedatectl >/dev/null 2>&1; then
    timedatectl show --property=Timezone --value 2>/dev/null || printf 'UTC'
  else
    printf 'UTC'
  fi
}

detect_host_ip() {
  # Try to detect the machine's primary IP address
  # Methods in order of preference (most reliable first)
  
  # Method 1: Use ip route to find the primary route's IP
  if command -v ip >/dev/null 2>&1; then
    local ip_addr
    ip_addr=$(ip route get 1 2>/dev/null | grep -oP '(?<=src\s)\S+' | head -1)
    if [[ -n "$ip_addr" && "$ip_addr" != "0.0.0.0" ]]; then
      printf '%s' "$ip_addr"
      return 0
    fi
  fi
  
  # Method 2: Use hostname -I (gets all IPs, use first one)
  if command -v hostname >/dev/null 2>&1; then
    local ip_addr
    ip_addr=$(hostname -I 2>/dev/null | awk '{print $1}')
    if [[ -n "$ip_addr" && "$ip_addr" != "0.0.0.0" ]]; then
      printf '%s' "$ip_addr"
      return 0
    fi
  fi
  
  # Fallback to .env value or generic default
  if [[ -n "${HOST_IP:-}" ]]; then
    printf '%s' "$HOST_IP"
  else
    printf '192.168.1.20'
  fi
}

prompt_value() {
  local variable_name="$1"
  local label="$2"
  local default_value="$3"
  local secret="${4:-false}"
  local value

  if [[ "$secret" == "true" ]]; then
    read -r -s -p "$label [$default_value]: " value
    echo
  else
    read -r -p "$label [$default_value]: " value
  fi

  if [[ -z "$value" ]]; then
    value="$default_value"
  fi

  printf -v "$variable_name" '%s' "$value"
}

prompt_yes_no() {
  local variable_name="$1"
  local label="$2"
  local default_value="$3"
  local value

  read -r -p "$label [$default_value]: " value
  value="${value:-$default_value}"
  case "$value" in
    [Yy]|[Yy][Ee][Ss]) printf -v "$variable_name" '%s' "yes" ;;
    [Nn]|[Nn][Oo]) printf -v "$variable_name" '%s' "no" ;;
    *)
      echo "Please answer yes or no."
      prompt_yes_no "$variable_name" "$label" "$default_value"
      ;;
  esac
}

existing_public_default="no"
if [[ -n "${PUBLIC_DOMAIN:-}" && "${PUBLIC_DOMAIN:-}" != "printer.example.com" ]]; then
  existing_public_default="yes"
fi

existing_camera_url="${EXTERNAL_WEBCAM_URL:-}"
current_printer_ip="${PRINTER_IP:-192.168.1.50}"
current_moonraker_port="${MOONRAKER_PORT:-7125}"
current_host_ip="$(detect_host_ip)"
current_timezone="$(default_timezone)"
current_mainsail_port="${MAINSAIL_PORT:-8080}"
current_public_domain="${PUBLIC_DOMAIN:-printer.example.com}"
current_certbot_email="${CERTBOT_EMAIL:-admin@example.com}"

cat <<'EOF'
QIDI Plus 4 Sidecar configuration wizard
----------------------------------------
Press Enter to keep the value shown in brackets.
EOF

echo
prompt_value PRINTER_IP "Printer / Moonraker IP" "$current_printer_ip"
prompt_value MOONRAKER_PORT "Moonraker port" "$current_moonraker_port"
prompt_value HOST_IP "Raspberry Pi / host IP" "$current_host_ip"
prompt_value TZ "Timezone" "$current_timezone"
prompt_value MAINSAIL_PORT "Mainsail port on the host" "$current_mainsail_port"
prompt_value EXTERNAL_WEBCAM_URL "External webcam URL (optional)" "$existing_camera_url"
prompt_yes_no ENABLE_PUBLIC "Enable public HTTPS with nginx + Certbot?" "$existing_public_default"

MAINSAIL_BIND_IP="0.0.0.0"
GO2RTC_BIND_IP="127.0.0.1"
GO2RTC_RTSP_BIND_IP="127.0.0.1"
GO2RTC_WEBRTC_BIND_IP="127.0.0.1"
EXPORTER_BIND_IP="127.0.0.1"
PUBLIC_DOMAIN=""
CERTBOT_EMAIL=""
PUBLIC_HTTP_BIND_IP="0.0.0.0"
PUBLIC_HTTP_PORT="80"
PUBLIC_HTTPS_BIND_IP="0.0.0.0"
PUBLIC_HTTPS_PORT="443"

if [[ "$ENABLE_PUBLIC" == "yes" ]]; then
  prompt_value PUBLIC_DOMAIN "Public domain" "$current_public_domain"
  prompt_value CERTBOT_EMAIL "Certbot email" "$current_certbot_email"
  MAINSAIL_BIND_IP="127.0.0.1"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/configure-env.sh
PRINTER_IP=$PRINTER_IP
MOONRAKER_PORT=$MOONRAKER_PORT
HOST_IP=$HOST_IP
TZ=$TZ

# Optional camera settings
EXTERNAL_WEBCAM_URL=$EXTERNAL_WEBCAM_URL
# CAMERA_SOURCE=auto

# Optional Obico placeholders
OBICO_AUTH_TOKEN=${OBICO_AUTH_TOKEN:-CHANGE_ME}
OBICO_SECRET_KEY=${OBICO_SECRET_KEY:-CHANGE_ME}

# Host port bindings
MAINSAIL_BIND_IP=$MAINSAIL_BIND_IP
MAINSAIL_PORT=$MAINSAIL_PORT
GO2RTC_BIND_IP=$GO2RTC_BIND_IP
GO2RTC_RTSP_BIND_IP=$GO2RTC_RTSP_BIND_IP
GO2RTC_WEBRTC_BIND_IP=$GO2RTC_WEBRTC_BIND_IP
EXPORTER_BIND_IP=$EXPORTER_BIND_IP

# Public reverse proxy with nginx + Certbot
PUBLIC_DOMAIN=$PUBLIC_DOMAIN
CERTBOT_EMAIL=$CERTBOT_EMAIL
PUBLIC_HTTP_BIND_IP=$PUBLIC_HTTP_BIND_IP
PUBLIC_HTTP_PORT=$PUBLIC_HTTP_PORT
PUBLIC_HTTPS_BIND_IP=$PUBLIC_HTTPS_BIND_IP
PUBLIC_HTTPS_PORT=$PUBLIC_HTTPS_PORT
EOF

echo
echo "Saved configuration to $ENV_FILE"
echo "Next steps:"
echo "  1. make validate"
echo "  2. make up"
if [[ "$ENABLE_PUBLIC" == "yes" ]]; then
  echo "  3. make public-up"
  echo "  4. make public-init-cert"
fi
